export const activitiesData = [
  {
    id: 1,
    title: "Borobudur Temple Tour",
    imageUrls: ["/assets/activities/borobudur.jpg"],
    price: 500000,
    price_discount: 450000,
    rating: "4.8",
    city: "Magelang",
    category: {
      name: "Heritage",
    },
  },
  {
    id: 2,
    title: "Malioboro Street Food Tour",
    imageUrls: ["/assets/activities/malioboro.jpg"],
    price: 300000,
    price_discount: 0,
    rating: "4.5",
    city: "Yogyakarta",
    category: {
      name: "Culinary",
    },
  },
  {
    id: 3,
    title: "Prambanan Temple Sunset Tour",
    imageUrls: ["/assets/activities/prambanan.jpg"],
    price: 400000,
    price_discount: 350000,
    rating: "4.7",
    city: "Sleman",
    category: {
      name: "Heritage",
    },
  },
  {
    id: 4,
    title: "Merapi Volcano Jeep Tour",
    imageUrls: ["/assets/activities/merapi.jpg"],
    price: 600000,
    price_discount: 0,
    rating: "4.9",
    city: "Sleman",
    category: {
      name: "Adventure",
    },
  },
  {
    id: 5,
    title: "Parangtritis Beach Sunset",
    imageUrls: ["/assets/activities/parangtritis.jpg"],
    price: 200000,
    price_discount: 180000,
    rating: "4.4",
    city: "Bantul",
    category: {
      name: "Nature",
    },
  },
  {
    id: 6,
    title: "Jomblang Cave Adventure",
    imageUrls: ["/assets/activities/jomblang.jpg"],
    price: 450000,
    price_discount: 0,
    rating: "4.6",
    city: "Gunungkidul",
    category: {
      name: "Adventure",
    },
  },
  {
    id: 7,
    title: "Taman Sari Water Castle",
    imageUrls: ["/assets/activities/tamansari.jpg"],
    price: 250000,
    price_discount: 225000,
    rating: "4.3",
    city: "Yogyakarta",
    category: {
      name: "Heritage",
    },
  },
  {
    id: 8,
    title: "Kalibiru National Park",
    imageUrls: ["/assets/activities/kalibiru.jpg"],
    price: 350000,
    price_discount: 0,
    rating: "4.7",
    city: "Kulon Progo",
    category: {
      name: "Nature",
    },
  },
];
